-- +goose Up
-- +goose StatementBegin
insert into book (title, author_full_name, country, century, image_key) values
('О всё видавшем','Неизвестный автор','Шумер',-18,'o_vsyo_vidavshem_neizvestnyy_avtor'),
('Книга Иова','Неизвестный автор','Держава Ахеменидов',-6,'kniga_iova_neizvestnyy_avtor'),
('Тысяча и одна ночь','Неизвестный автор','Арабский халифат',8,'tysyacha_i_odna_noch_neizvestnyy_avtor'),
('Сага о Ньяле','Неизвестный автор','Исландия',13,'saga_o_nyale_neizvestnyy_avtor'),
('Божественная комедия','Данте Алигьери','Италия',13,'bozhestvennaya_komediya_dante_aligeri'),
('Сказки','Ханс Кристиан Андерсен','Дания',19,'skazki_khans_kristian_andersen'),
('И пришло разрушение','Чинуа Ачебе','Нигерия',20,'i_prishlo_razrushenie_chinua_achebe'),
('Отец Горио','Оноре де Бальзак','Франция',19,'otets_gorio_onore_de_balzak'),
('Моллой','Сэмюэл Беккет','Ирландия',20,'molloy_semyuel_bekket'),
('Мэлон умирает','Сэмюэл Беккет','Ирландия',20,'melon_umiraet_semyuel_bekket'),
('Безымянный','Сэмюэл Беккет','Ирландия',20,'bezymyannyy_semyuel_bekket'),
('Декамерон','Джованни Боккаччо','Италия',14,'dekameron_dzhovanni_bokkachcho'),
('Вымыслы','Хорхе Луис Борхес','Аргентина',20,'vymysly_khorkhe_luis_borkhes'),
('Грозовой перевал','Эмили Бронте','Великобритания',19,'grozovoy_pereval_emili_bronte'),
('Рамаяна','Вальмики','Индия',-3,'ramayana_valmiki'),
('Энеида','Вергилий','Римская империя',-1,'eneida_vergiliy'),
('Миссис Дэллоуэй','Вирджиния Вулф','Великобритания',20,'missis_dellouey_virdzhiniya_vulf'),
('На маяк','Вирджиния Вулф','Великобритания',20,'na_mayak_virdzhiniya_vulf'),
('Махабхарата','Вьяса','Индия',-4,'makhabkharata_vyasa'),
('Голод','Кнут Гамсун','Норвегия',19,'golod_knut_gamsun'),
('Цыганское романсеро','Федерико Гарсиа Лорка','Испания',20,'tsyganskoe_romansero_federiko_garsia_lorka'),
('Сто лет одиночества','Габриэль Гарсиа Маркес','Колумбия',20,'sto_let_odinochestva_gabriel_garsia_markes'),
('Любовь во время чумы','Габриэль Гарсиа Маркес','Колумбия',20,'lyubov_vo_vremya_chumy_gabriel_garsia_markes'),
('Фауст','Иоганн Вольфганг фон Гёте','Германия',19,'faust_iogann_volfgang_fon_gyote'),
('Тропы по большому сертану','Жуан Гимарайнс Роза','Бразилия',20,'tropy_po_bolshomu_sertanu_zhuan_gimarayns_roza'),
('Мёртвые души','Николай Васильевич Гоголь','Россия',19,'myortvye_dushi_nikolay_vasilevich_gogol'),
('Илиада','Гомер','Смирна',-9,'iliada_gomer'),
('Одиссея','Гомер','Смирна',-8,'odisseya_gomer'),
('Жестяной барабан','Гюнтер Грасс','Германия',20,'zhestyanoy_baraban_gyunter_grass'),
('Берлин Александрплац','Альфред Дёблин','Германия',20,'berlin_aleksandrplats_alfred_dyoblin'),
('Улисс','Джеймс Джойс','Ирландия',20,'uliss_dzheyms_dzhoys'),
('Жак-фаталист и его хозяин','Дени Дидро','Франция',18,'zhak_fatalist_i_ego_khozyain_deni_didro'),
('Большие надежды','Чарльз Диккенс','Великобритания',19,'bolshie_nadezhdy_charlz_dikkens'),
('Преступление и наказание','Фёдор Достоевский','Россия',19,'prestuplenie_i_nakazanie_fyodor_dostoevskiy'),
('Идиот','Фёдор Достоевский','Россия',19,'idiot_fyodor_dostoevskiy'),
('Бесы','Фёдор Достоевский','Россия',19,'besy_fyodor_dostoevskiy'),
('Братья Карамазовы','Фёдор Достоевский','Россия',19,'bratya_karamazovy_fyodor_dostoevskiy'),
('Медея','Еврипид','Афины',-5,'medeya_evripid'),
('Самопознание Дзено','Итало Звево','Австро-Венгрия',20,'samopoznanie_dzeno_italo_zvevo'),
('Кукольный дом','Генрик Ибсен','Норвегия',19,'kukolnyy_dom_genrik_ibsen'),
('Стон горы','Ясунари Кавабата','Япония',20,'ston_gory_yasunari_kavabata'),
('Невероятные похождения Алексиса Зорбаса','Никос Казандзакис','Греция',20,'neveroyatnye_pokhozhdeniya_aleksisa_zorbasa_nikos_kazandzakis'),
('Шакунтала','Калидаса','Индия',-1,'shakuntala_kalidasa'),
('Посторонний','Альбер Камю','Франция',20,'postoronniy_alber_kamyu'),
('Рассказы','Франц Кафка','Австро-Венгрия',20,'rasskazy_frants_kafka'),
('Процесс','Франц Кафка','Австро-Венгрия',20,'protsess_frants_kafka'),
('Замок','Франц Кафка','Австро-Венгрия',20,'zamok_frants_kafka'),
('Ностромо','Джозеф Конрад','Великобритания',20,'nostromo_dzhozef_konrad'),
('Самостоятельные люди','Халлдор Кильян Лакснесс','Исландия',20,'samostoyatelnye_lyudi_khalldor_kilyan_laksness'),
('Стихи','Джакомо Леопарди','Италия',19,'stikhi_dzhakomo_leopardi'),
('Золотая тетрадь','Дорис Лессинг','Великобритания',20,'zolotaya_tetrad_doris_lessing'),
('Пеппи Длинныйчулок','Астрид Линдгрен','Швеция',20,'peppi_dlinnychulok_astrid_lindgren'),
('Сыновья и любовники','Дэвид Герберт Лоуренс','Великобритания',20,'synovya_i_lyubovniki_devid_gerbert_lourens'),
('Записки сумасшедшего','Лу Синь','Китай',20,'zapiski_sumasshedshego_lu_sin'),
('Будденброки','Томас Манн','Германия',20,'buddenbroki_tomas_mann'),
('Волшебная гора','Томас Манн','Германия',20,'volshebnaya_gora_tomas_mann'),
('История нашей улицы','Нагиб Махфуз','Египет',20,'istoriya_nashey_ulitsa_nagib_makhfuz'),
('Моби Дик','Герман Мелвилл','США',19,'mobi_dik_german_melvill'),
('Опыты','Мишель де Монтень','Франция',16,'opyty_mishel_de_monten'),
('История','Эльза Моранте','Италия',20,'istoriya_elza_morante'),
('Возлюбленная','Тони Моррисон','США',20,'vozlyublennaya_toni_morrison'),
('Человек без свойств','Роберт Музиль','Австрия',20,'chelovek_bez_svoystv_robert_muzil'),
('Лолита','Владимир Набоков','Российская империя',20,'lolita_vladimir_nabokov'),
('Метаморфозы','Публий Овидий Назон','Римская империя',1,'metamorfozy_publiy_ovidiy_nazon'),
('1984','Джордж Оруэлл','Великобритания',20,'1984_dzhordzh_oruell'),
('Книга непокоя','Фернанду Пессоа','Португалия',20,'kniga_nepokoya_fernandu_pessoa'),
('Рассказы','Эдгар Аллан По','США',19,'rasskazy_edgar_allan_po'),
('В поисках утраченного времени','Марсель Пруст','Франция',20,'v_poiskakh_utrachennogo_vremeni_marsel_prust'),
('Гаргантюа и Пантагрюэль','Франсуа Рабле','Франция',16,'gargantyua_i_pantagryuel_fransua_rable'),
('Педро Парамо','Хуан Рульфо','Мексика',20,'pedro_paramo_khuan_rulfo'),
('Маснави','Джалаладдин Руми','Государство Хулагуидов',13,'masnavi_dzhalaladdin_rumi'),
('Дети полуночи','Салман Рушди','Британская Индия',20,'deti_polunochi_salman_rushdi'),
('Гордость и предубеждение','Джейн Остин','Великобритания',19,'gordost_i_predubezhdenie_dzheyn_ostin'),
('Бустан','Саади','Государство Хулагуидов',13,'bustan_saadi'),
('Сезон паломничества на Север','Тайиб Салих','Судан',20,'sezon_palomnichestva_na_sever_tayib_salikh'),
('Слепота','Жозе Сарамаго','Португалия',20,'slepota_zhoze_saramago'),
('Путешествия Гулливера','Джонатан Свифт','Ирландия',18,'puteshestviya_gullivera_dzhonatan_svift'),
('Путешествие на край ночи','Луи-Фердинанд Селин','Франция',20,'puteshestvie_na_kray_nochi_lui_ferdinand_selin'),
('Хитроумный идальго Дон Кихот Ламанчский','Мигель де Сервантес','Испания',17,'khitroumnyy_idalgo_don_kikhot_lamanchskiy_migel_de_servantes'),
('Повесть о блистательном принце Гэндзи','Мурасаки Сикибу','Япония',11,'povest_o_blistatelnom_printse_gendzi_murasaki_sikibu'),
('Эдип-царь','Софокл','Афины',-5,'edip_tsar_sofokl'),
('Красное и чёрное','Стендаль','Франция',19,'krasnoe_i_chernoe_stendal'),
('Жизнь и мнения Тристрама Шенди, джентльмена','Лоренс Стерн','Англия',18,'zhizn_i_mneniya_tristrama_shendi_dzhentlmena_lorens_stern'),
('Приключения Гекльберри Финна','Марк Твен','США',19,'priklyucheniya_geklberri_finna_mark_tven'),
('Война и мир','Лев Толстой','Россия',19,'voyna_i_mir_lev_tolstoy'),
('Анна Каренина','Лев Толстой','Россия',19,'anna_karenina_lev_tolstoy'),
('Смерть Ивана Ильича','Лев Толстой','Россия',19,'smert_ivana_ilicha_lev_tolstoy'),
('Листья травы','Уолт Уитмен','США',19,'listya_travy_uolt_uitmen'),
('Госпожа Бовари','Гюстав Флобер','Франция',19,'gospozha_bovari_gyustav_flober'),
('Воспитание чувств','Гюстав Флобер','Франция',19,'vospitanie_chuvstv_gyustav_flober'),
('Авессалом, Авессалом!','Уильям Фолкнер','США',20,'avessalom_avessalom_uilyam_folkner'),
('Шум и ярость','Уильям Фолкнер','США',20,'shum_i_yarost_uilyam_folkner'),
('Старик и море','Эрнест Хемингуэй','США',20,'starik_i_more_ernest_kheminguey'),
('Стихотворения','Пауль Целан','Румыния',20,'stikhotvoreniya_paul_tselan'),
('Рассказы','Антон Чехов','Россия',19,'rasskazy_anton_chekhov'),
('Кентерберийские рассказы','Джеффри Чосер','Англия',14,'kenterberiyskie_rasskazy_dzheffri_choser'),
('Гамлет','Уильям Шекспир','Англия',17,'gamlet_uilyam_shekspir'),
('Король Лир','Уильям Шекспир','Англия',17,'korol_lir_uilyam_shekspir'),
('Отелло','Уильям Шекспир','Англия',17,'otello_uilyam_shekspir'),
('Миддлмарч','Джордж Элиот','Великобритания',19,'middlmarch_dzhordzh_eliot'),
('Человек-невидимка','Ральф Эллисон','США',20,'chelovek_nevidimka_ralf_ellison'),
('Воспоминания Адриана','Маргерит Юрсенар','Франция',20,'vospominaniya_adriana_margerit_yursenar');


-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
delete from book;
-- +goose StatementEnd
